spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .html
  datasource:
    url: jdbc:h2:tcp://localhost/~/knut
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  header: Authorization
#  secret: 7Ju5IOqwnOuwnOydhCDspJHsi6zsnLzroZwg7Iqk7ZSE66eBIO2UhOugiOyehOybjO2BrOulvCDsnbTsmqntlZwg66Gc6re47J24IO2PvOqzvCDqsJnsnYAg6rCE64uo7ZWcIOq4sOyIoOydhCDqtaztmITtlojsirXri4jri6QuIOq3uOumrOqzoCDstpTqsIDroZwgSlNQ7JmAIFNlcnZsZXTrpbwg7J207Jqp7ZWY7JesIOqwnOuwnO2WiOqzoCDspJHqsITsl5Ag64Sk7Yq47JuM7YGs7JeQIOydtOuhoOyXkCDrjIDtlbTshJwg6rO167aA7ZWY66mwIOydtO2VtOugpeydhCDsi6ztmZQg64uo6rOE66GcIOqzoOywqeyLnO2CrCDsiJgg7J6I64qUIOqzhOq4sOqwgCDrkJDsirXri4jri6QuIOydtOulvCDqs4TquLDroZwg64Sk7Yq47JuM7YGs6rSA66as7IKsIDLquIkg7ZWE6riw7Iuc7ZeY7JeQ64+EIOu2meydgCDqsr3tl5jsnbQg7J6I7Iq164uI64ukLiDtm4Tsl5Ag7ISc67KEIOyatOyaqeydhCDtlZjquLAg7JyE7ZW0IOumrOuIheyKpCDquLDrs7gg66qF66C57Ja066W8IOyVjOqzoCDsi6TsoJwg7Jq07JiBIOykkeyduCDrqZTsnbwg7ISc67KE7JeQIOuwseyLoOydhCDshKTsuZjtlZjqs6Ag6rCE64uo7ZWcIO2ZmOqyveyEpOygleydhCDqsoDsg4nrj4Tqtazrpbwg7J207Jqp7ZWY7JesIO2VhOyalOyXkCDrlLDrnbwg67CU6r646rOgIOuztOyViOyhsOy5mCDrqZTribTslrzsl5Ag65Sw65287IScIOuYkeqwmeydtCDss5Drs7TrqbAg6rCQ7IKsIOuwm+ydhCDrlYwg7L2U7Lmt7J2EIOuwm+q4sOuPhCDtlbTrs7TslZjsirXri4jri6QuIOuYkCDshJzrsoTsl5Ag64yA7ZWcIOygleuztOuztOyViOydhCDsnITtlbQgdXRt6rO8IG5hY+qwmeydgCDsgqzsmqnsnpAg67O07Zi466W8IOychO2VnCDrsKntmZTrsr3qs7wg7Jyg7KCAIOq0gOumrOulvCDtlbTrs7TslZjsnLzrqbAgY2ljc28g64Sk7Yq47JuM7YGsIOyepeu5hOuhnCDrgrTrtoAgaXDrs7TtmLjrpbwg7JyE7ZW0IOqwhOuLqO2VnCDsoJXrs7Qg7KGw7ZqM66W8IO2VoCDsiJgg7J6I7Iq164uI64ukLg==
  token-validity-in-seconds: 86400